#!/bin/bash
# public dns
AWS_EUW_A=ec2-user@ec2-3-8-126-219.eu-west-2.compute.amazonaws.com
AWS_EUW_B=ec2-user@ec2-18-130-67-33.eu-west-2.compute.amazonaws.com
AWS_EUW_C=ec2-user@ec2-3-8-89-77.eu-west-2.compute.amazonaws.com

# default server
AWS_SERVER=AWS_EUW_${1:-C}

# security group
AWS_SG=sg-066c37d90319bbf39
