{ table: 'margin',
 action: 'partial',
 keys: [ 'account', 'currency' ],
 types:
  { account: 'long',
    currency: 'symbol',
    riskLimit: 'long',
    prevState: 'symbol',
    state: 'symbol',
    action: 'symbol',
    amount: 'long',
    pendingCredit: 'long',
    pendingDebit: 'long',
    confirmedDebit: 'long',
    prevRealisedPnl: 'long',
    prevUnrealisedPnl: 'long',
    grossComm: 'long',
    grossOpenCost: 'long',
    grossOpenPremium: 'long',
    grossExecCost: 'long',
    grossMarkValue: 'long',
    riskValue: 'long',
    taxableMargin: 'long',
    initMargin: 'long',
    maintMargin: 'long',
    sessionMargin: 'long',
    targetExcessMargin: 'long',
    varMargin: 'long',
    realisedPnl: 'long',
    unrealisedPnl: 'long',
    indicativeTax: 'long',
    unrealisedProfit: 'long',
    syntheticMargin: 'long',
    walletBalance: 'long',
    marginBalance: 'long',
    marginBalancePcnt: 'float',
    marginLeverage: 'float',
    marginUsedPcnt: 'float',
    excessMargin: 'long',
    excessMarginPcnt: 'float',
    availableMargin: 'long',
    withdrawableMargin: 'long',
    timestamp: 'timestamp',
    grossLastValue: 'long',
    commission: 'float' },
 foreignKeys: {},
 attributes: { account: 'sorted', currency: 'grouped' },
 filter: { account: 153475 },
 data:
  [ { account: 153475,
      currency: 'XBt',
      riskLimit: 1000000000000,
      prevState: '',
      state: '',
      action: '',
      amount: 105527993,
      pendingCredit: 0,
      pendingDebit: 0,
      confirmedDebit: 0,
      prevRealisedPnl: -19,
      prevUnrealisedPnl: 0,
      grossComm: -14029,
      grossOpenCost: 0,
      grossOpenPremium: 0,
      grossExecCost: 0,
      grossMarkValue: 55734000,
      riskValue: 55734000,
      taxableMargin: 0,
      initMargin: 0,
      maintMargin: 55734000,
      sessionMargin: 0,
      targetExcessMargin: 0,
      varMargin: 0,
      realisedPnl: 14029,
      unrealisedPnl: -382000,
      indicativeTax: 0,
      unrealisedProfit: 0,
      syntheticMargin: null,
      walletBalance: 105542022,
      marginBalance: 105160022,
      marginBalancePcnt: 1,
      marginLeverage: 0.5299922816676474,
      marginUsedPcnt: 0.53,
      excessMargin: 49426022,
      excessMarginPcnt: 0.8868,
      availableMargin: 49426022,
      withdrawableMargin: 49426022,
      timestamp: '2019-02-10T09:00:00.494Z',
      grossLastValue: 55734000,
      commission: null } ] } 
